from typing import Any

from agent_ready_tools.tools.procurement.common_dataclasses import ToolResponse
from agent_ready_tools.tools.procurement.purchase_support.coupa.purchase_support_dataclasses import (
    CoupaAddress,
    CoupaOrderLine,
    CoupaOrderLines,
    CoupaPurchaseOrder,
    CoupaRequisition,
    CoupaRequisitionLine,
)
from agent_ready_tools.utils.tool_snapshot.patch import patch_tool_id


@patch_tool_id(tool_name="coupa_get_purchase_order_by_id")
def fixture_coupa_get_purchase_order_by_id(*args: Any, **kwargs: Any) -> ToolResponse:
    """Mock fixture for coupa_get_purchase_order_by_id."""
    return ToolResponse(
        success=True,
        message="Purchase order retrieved successfully.",
        content=CoupaPurchaseOrder(
            purchase_order_id=4173,
            po_number="4173",
            created_by="ssingh",
            updated_by="IBMFunctionalUser",
            created_at="2025-04-22T02:23:28-07:00",
            updated_at="2025-12-02T11:10:14-08:00",
            status="issued",
            transmission_status="sent_via_email",
            exported=False,
            ship_to_attention="Meg(CEO) Jordan",
            requested_by="Meg(CEO) Jordan",
            payment_method="invoice",
            currency="USD",
            estimated_tax_amount="0.00",
            total_with_estimated_tax="62000.00",
            requisition_number=5331,
            shipping_address=CoupaAddress(
                id=231195,
                location_code="ship-to-5331",
                street1="555 Bailey Ave",
                city="San Jose",
                state="CA",
                postal_code="95141",
                country="United States",
            ),
            supplier_id=38,
            supplier_name="Apple (USA)",
            requisition=CoupaRequisition(
                id=5331,
                created_at="2025-04-06T15:11:47-07:00",
                updated_at="2025-04-25T15:51:04-07:00",
                created_by="IBMFunctionalUser",
                updated_by="ssingh",
                requested_by="mjordan",
                status="received",
                currency="USD",
                line_count=4,
                total_with_estimated_tax="62000.00",
                need_by_date=None,
                business_unit=None,
                business_purpose=None,
                ship_to_address=CoupaAddress(
                    id=231195,
                    location_code="ship-to-5331",
                    street1="555 Bailey Ave",
                    city="San Jose",
                    state="CA",
                    postal_code="95141",
                    country="United States",
                ),
                ship_to_attention="Meg(CEO) Jordan",
                current_approval=None,
                approval_id_list=[85675],
                requisition_lines=[
                    CoupaRequisitionLine(
                        id=9942,
                        description="MacBook Pro Retina - 15-inch",
                        unit_price=2000.0,
                        currency="USD",
                        line_type="RequisitionQuantityLine",
                        line_num=1,
                        total_with_estimated_tax="20000.00",
                        item_id=None,
                        item_name=None,
                        item_description=None,
                        item_number=None,
                        item_manufacturer_name=None,
                        item_manufacturer_part_number=None,
                        supplier_id=38,
                        billing_account_id=1540,
                        quantity="10.0",
                        uom="Each",
                        commodity="Hardware",
                        supplier_part_number=None,
                        shipping_terms="Standard",
                        payment_terms="Net 30",
                        need_by_date=None,
                        transmission_method="supplier_default",
                        manufacturer_name=None,
                        manufacturer_part_number=None,
                    ),
                    CoupaRequisitionLine(
                        id=9943,
                        description="MacBook Pro Retina - 15-inch",
                        unit_price=2000.0,
                        currency="USD",
                        line_type="RequisitionQuantityLine",
                        line_num=2,
                        total_with_estimated_tax="20000.00",
                        item_id=None,
                        item_name=None,
                        item_description=None,
                        item_number=None,
                        item_manufacturer_name=None,
                        item_manufacturer_part_number=None,
                        supplier_id=38,
                        billing_account_id=1540,
                        quantity="10.0",
                        uom="Each",
                        commodity="Hardware",
                        supplier_part_number=None,
                        shipping_terms="Standard",
                        payment_terms="Net 30",
                        need_by_date=None,
                        transmission_method="supplier_default",
                        manufacturer_name=None,
                        manufacturer_part_number=None,
                    ),
                    CoupaRequisitionLine(
                        id=9944,
                        description="MacBook Pro Retina - 15-inch",
                        unit_price=2000.0,
                        currency="USD",
                        line_type="RequisitionQuantityLine",
                        line_num=3,
                        total_with_estimated_tax="20000.00",
                        item_id=None,
                        item_name=None,
                        item_description=None,
                        item_number=None,
                        item_manufacturer_name=None,
                        item_manufacturer_part_number=None,
                        supplier_id=38,
                        billing_account_id=1540,
                        quantity="10.0",
                        uom="Each",
                        commodity="Hardware",
                        supplier_part_number=None,
                        shipping_terms="Standard",
                        payment_terms="Net 30",
                        need_by_date=None,
                        transmission_method="supplier_default",
                        manufacturer_name=None,
                        manufacturer_part_number=None,
                    ),
                    CoupaRequisitionLine(
                        id=9945,
                        description="MacBook Pro Retina - 15-inch",
                        unit_price=2000.0,
                        currency="USD",
                        line_type="RequisitionQuantityLine",
                        line_num=4,
                        total_with_estimated_tax="2000.00",
                        item_id=None,
                        item_name=None,
                        item_description=None,
                        item_number=None,
                        item_manufacturer_name=None,
                        item_manufacturer_part_number=None,
                        supplier_id=38,
                        billing_account_id=1540,
                        quantity="1.0",
                        uom="Each",
                        commodity="Hardware",
                        supplier_part_number=None,
                        shipping_terms="Standard",
                        payment_terms="Net 30",
                        need_by_date=None,
                        transmission_method="supplier_default",
                        manufacturer_name=None,
                        manufacturer_part_number=None,
                    ),
                ],
            ),
            order_lines=CoupaOrderLines(
                order_lines=[
                    CoupaOrderLine(
                        order_line_id=6085,
                        order_line_description="MacBook Pro Retina - 15-inch",
                        order_line_type="OrderQuantityLine",
                        order_line_num="1",
                        item_description=None,
                        quantity="10.0",
                        unit=None,
                        price="2000.00",
                        total="20000.00",
                        account_id=1540,
                        account_type_id=1,
                        uom_code="EA",
                        estimated_tax_amount="0.00",
                        total_with_estimated_tax="20000.00",
                        amount_received=10.0,
                        receipt_approval_required=False,
                        supplier_part_number=None,
                        supplier_auxiliary_part_number=None,
                        commodity="Hardware",
                        manufacturer_name=None,
                        manufacturer_part_number=None,
                        need_by_date=None,
                        savings_percent="0.0",
                        billing_account_id=1540,
                        period=None,
                    ),
                    CoupaOrderLine(
                        order_line_id=6086,
                        order_line_description="MacBook Pro Retina - 15-inch",
                        order_line_type="OrderQuantityLine",
                        order_line_num="2",
                        item_description=None,
                        quantity="10.0",
                        unit=None,
                        price="2000.00",
                        total="20000.00",
                        account_id=1540,
                        account_type_id=1,
                        uom_code="EA",
                        estimated_tax_amount="0.00",
                        total_with_estimated_tax="20000.00",
                        amount_received=10.0,
                        receipt_approval_required=False,
                        supplier_part_number=None,
                        supplier_auxiliary_part_number=None,
                        commodity="Hardware",
                        manufacturer_name=None,
                        manufacturer_part_number=None,
                        need_by_date=None,
                        savings_percent="0.0",
                        billing_account_id=1540,
                        period=None,
                    ),
                    CoupaOrderLine(
                        order_line_id=6087,
                        order_line_description="MacBook Pro Retina - 15-inch",
                        order_line_type="OrderQuantityLine",
                        order_line_num="3",
                        item_description=None,
                        quantity="10.0",
                        unit=None,
                        price="2000.00",
                        total="20000.00",
                        account_id=1540,
                        account_type_id=1,
                        uom_code="EA",
                        estimated_tax_amount="0.00",
                        total_with_estimated_tax="20000.00",
                        amount_received=10.0,
                        receipt_approval_required=False,
                        supplier_part_number=None,
                        supplier_auxiliary_part_number=None,
                        commodity="Hardware",
                        manufacturer_name=None,
                        manufacturer_part_number=None,
                        need_by_date=None,
                        savings_percent="0.0",
                        billing_account_id=1540,
                        period=None,
                    ),
                    CoupaOrderLine(
                        order_line_id=6088,
                        order_line_description="MacBook Pro Retina - 15-inch",
                        order_line_type="OrderQuantityLine",
                        order_line_num="4",
                        item_description=None,
                        quantity="1.0",
                        unit=None,
                        price="2000.00",
                        total="2000.00",
                        account_id=1540,
                        account_type_id=1,
                        uom_code="EA",
                        estimated_tax_amount="0.00",
                        total_with_estimated_tax="2000.00",
                        amount_received=1.0,
                        receipt_approval_required=False,
                        supplier_part_number=None,
                        supplier_auxiliary_part_number=None,
                        commodity="Hardware",
                        manufacturer_name=None,
                        manufacturer_part_number=None,
                        need_by_date=None,
                        savings_percent="0.0",
                        billing_account_id=1540,
                        period=None,
                    ),
                ]
            ),
            shipping_terms="Fedex",
            payment_terms="Net 15",
            department=None,
        ),
        content_details=None,
    )
