[mypy]
ignore_missing_imports = true
follow_imports = silent
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = false
implicit_reexport = false
show_error_context = true
namespace_packages = true

pretty = true

# still unstable.
# warn_unreachable = true

[mypy-pants.*]
ignore_missing_imports = false

[mypy-mcd.techlabs.*]
ignore_missing_imports = false

# generic type inference for hamcrest functions is broken for python 3.8
# e.g. "incompatible type "Matcher[str]"; expected "Matcher[<nothing>]""
[mypy-hamcrest.*]
implicit_reexport = true
follow_imports = skip
follow_imports_for_stubs = True

[mypy-tenacity.*]
implicit_reexport = true

[mypy-git.*]
implicit_reexport = true

[mypy-curtsies.*]
implicit_reexport = true

[mypy-pyinstrument.*]
implicit_reexport = true

# torch is messed up, they are working on fixing it
# https://discuss.pytorch.org/t/pytorch-type-annotations-are-buggy-how-to-suppress-mypy-errors/61484/6
[mypy-torch.*]
follow_imports = skip
follow_imports_for_stubs = True

# pytermgui is messed up, they aren't working on fixing it
[mypy-pytermgui.*]
follow_imports = skip
follow_imports_for_stubs = True
